# Site settings
name: G2K
baseurl: ""
url: "https://teachers.gateway2khmer.com"
description: ""
author: "Yong"
title: "For G2K Teachers"
permalink: :title
email: tech@gateway2khmer.com

# social
github:
  username: username

favicon: "/images/G2K-Favicon.jpg" # relative path to site's favicon

# Zoom placement test link
placement-link: https://zoom.us/j/99246480204
placement-text: Placement Test

# Staff Appraisal link
staff-appraisal: https://forms.gle/KXHVyAUPbammPujJA
gdrive: https://docs.google.com/spreadsheets/d/

copyright: G2K, Gateway To Khmer.

# stop the warning message for _data/2022-.yml
#liquid:
#  error_mode: lax
